Traceback (most recent call last):
  File "cifar10_experiments.py", line 10, in <module>
    from lib.experiments import load_dataset, run_wcl, train_with_original, run_pop, run_egdis, run_cl, run_wcl2, run_wcl3
  File "/home/s1572869/MSc_Data_Reduction/lib/experiments.py", line 12, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/s1572869/miniconda3/envs/mlp/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/s1572869/miniconda3/envs/mlp/lib/python3.7/site-packages/sklearn/base.py", line 20, in <module>
    from .utils import _IS_32BIT
  File "/home/s1572869/miniconda3/envs/mlp/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 20, in <module>
    from scipy.sparse import issparse
  File "/home/s1572869/miniconda3/envs/mlp/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/home/s1572869/miniconda3/envs/mlp/lib/python3.7/site-packages/scipy/sparse/base.py", line 7, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/home/s1572869/miniconda3/envs/mlp/lib/python3.7/site-packages/scipy/_lib/_numpy_compat.py", line 16, in <module>
    _assert_warns = np.testing.assert_warns
AttributeError: module 'numpy.testing' has no attribute 'assert_warns'
